pwd = "pwd"

[debug]
deployd = "cargo run --manifest-path utils/deploy/d/Cargo.toml"
"apps/dev" = "run build apps/dev && run build desktop && RUST_LOG=info target/debug/puzzle run target/wasm32-unknown-unknown/debug/dev.wasm"
web = "cd runners/web && trunk serve --open"

[build.desktop]
index = "cargo build --manifest-path runners/desktop/Cargo.toml"
release = "cargo build --manifest-path runners/desktop/Cargo.toml --release"

[build.web]
index = "cd runners/web && trunk build"
release = "cd runners/web && trunk build --release"

[build."apps/dev"]
index = "cargo build --manifest-path apps/dev/Cargo.toml --target=wasm32-unknown-unknown"
release = "cargo build --manifest-path apps/dev/Cargo.toml --target=wasm32-unknown-unknown --release"

[build.server]
index = "cargo build --manifest-path net/server/Cargo.toml"
release = "cargo build --manifest-path net/server/Cargo.toml --release"

[dist]
index = """
run build web release &&
if [ -d dist ];
	then rm -r dist;
fi &&
mkdir -p dist &&
cp -r runners/web/dist dist/static &&
run build server release &&
cp target/release/net_server dist/net_server
"""

# this only deployd locally btw
deploy = """
run dist &&
cargo run --manifest-path utils/deploy/ctl/Cargo.toml dist-dir `realpath dist` net_server
"""
