[scripts]
build-desktop = "cargo build --manifest-path runners/desktop/Cargo.toml"
build-dev = "cargo build --manifest-path apps/dev/Cargo.toml --target=wasm32-unknown-unknown"

watch-all = "cargo watch --watch runners/desktop --watch runners/wasmtime_common -s 'cargo run --manifest-path runners/desktop/Cargo.toml -- cargo-watch -C apps/dev -t target --watch sdk/puzzle_sdk_log'"
dev = "run build-dev && run build-desktop && RUST_LOG=info target/debug/puzzle run target/wasm32-unknown-unknown/debug/dev.wasm"

install-desktop = "cargo install --path=runners/desktop"

server = "cargo build --manifest-path net/server/Cargo.toml"
web = "cd runners/web && trunk build"
dist = "run web --release && rm -r dist && mkdir -p dist && cp -r runners/web/dist dist/static && run server --release && cp target/release/net_server dist/net_server"

deploy_local = "run dist && cargo run --manifest-path utils/deploy/ctl/Cargo.toml -- dist-dir ../../../dist net_server"
