[package]
name = "id_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puzzle_common.workspace = true
id_common = { path = "../common" }
wasmtime.workspace = true
thiserror.workspace = true
