[package]
name = "jigsaw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgfx-rs = "0.19.0"
glfw = "0.54.0"
log = "0.4.20"
raw-window-handle = "0.5.0"
thiserror = "1.0.50"
