[package]
name = "jigsaw"
version = "0.1.0"
edition = "2021"

[features]
wasm = ["dep:wasmtime"]

[dependencies]
bgfx-rs = "0.19.0"
glfw = "0.54.0"
log = "0.4.20"
raw-window-handle = "0.5.0"
thiserror = "1.0.50"
wasmtime = { version = "15.0.1", optional = true }
