name: check
on:
  push:
    branches:
      - '*'
jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: whoami
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo check
        run: cargo check
