name: deploy_server
on:
  push:
    branches:
      - wasi # dont forget
jobs:
  deploy_server:
    runs-on: self-hosted
    steps:
      - name: compile, run & disown
        run: |
          cd puzzle && ls -la
