name: deploy
on:
  push:
    branches:
      - wasi # dont forget
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: git clone git@github.com:manen/puzzle && cd puzzle && cargo build --manifest-path server/server/Cargo.toml --release && pkill server; run server
