name: deploy
on:
  push:
    branches:
      - wasi # dont forget
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: rm -rf puzzle; git clone git@github.com:manen/puzzle && cd puzzle && git switch wasi && cargo build --manifest-path net/server/Cargo.toml --release && pkill server; nohup run server & disown
