name: deploy_server
on:
  push:
    branches:
      - wasi # dont forget
jobs:
  deploy_server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: compile, run & disown
        run: |
          cd puzzle/net/server
          cargo build --release
          nohup cargo run --release
