name: deploy_server
on:
  push:
    branches:
      - wasi # dont forget
jobs:
  deploy_server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: compile, run & disown
        run: |
          cd net/server
          cargo build --release
          pkill net_server
          nohup cargo run --release > net_server.$(date +%s).log 2> net_server.$(date +%s).err < /dev/null &
