name: deploy_server
on:
  # workflow_run:
  #   workflows: ["test"]
  #   types:
  #     - completed
  push:
    branches:
      - 'wasi'

jobs:
  deploy_server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: compile, run & disown
        run: |
          cargo install --path net/server && pkill net_server && nohup net_server > net_server.$(date +%s).log 2> net_server.$(date +%s).err < /dev/null &
