name: push
on:
  push:
    branches:
      - 'beta'
jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo check
        run: cargo check

  test:
    needs: check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo test
        run: cargo test

  # # the reason all this is commented out is because we can't interact with systemctl
  # # from the actions shell or something idk but deployd updates will have to be manual sadly 
  #
  # deployd:
  #   needs: test
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: create target symlink
  #       run: |
  #         ln -s /target ./target

  #     - name: cargo install deployd
  #       run: cargo install --path utils/deploy/d

  #     - name: cargo install deployctl
  #       run: cargo install --path utils/deploy/ctl

  server:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create target symlink
        run: |
          ln -s /target ./target
      
      - name: compile web and deploy net_server
        run: run dist deploy
