name: push
on:
  push:
    branches:
      - '*'
jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo check
        run: cargo check

  test:
    needs: check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo test
        run: cargo test
