name: test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: create target symlink
        run: |
          if [ ! -d /tmp/target ]; then mkdir -p /tmp/target; fi
          ln -s /tmp/target ./target
          
      - name: cargo test
        run: cargo test
