name: test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: create target symlink
        run: |
          ln -s /target ./target

      - name: cargo test
        run: cargo test
